syntax = "proto3";

package az.fitnest.media;

option java_multiple_files = true;
option java_package = "az.fitnest.media.grpc";
option java_outer_classname = "MediaServiceProto";
option go_package = "github.com/fitnest/media-service/internal/pb/mediapb;mediapb";

service MediaService {
  rpc UploadImage(UploadImageRequest) returns (MediaUploadResponse);
  rpc DeleteFiles(DeleteFilesRequest) returns (MediaDeleteResponse);
}

message UploadImageRequest {
  bytes image_data = 1;
  string filename = 2;
  string content_type = 3;
}

message FileDetails {
  string fs_id = 1;
  string path = 2;
  string server_filename = 3;
  int64 size = 4;
  string thumbnail_url = 5;
}

message MediaUploadResponse {
  bool success = 1;
  string message = 2;
  FileDetails data = 3;
}

message DeleteFilesRequest {
  repeated string file_paths = 1;
}

message MediaDeleteResponse {
  bool success = 1;
  string message = 2;
  int32 data = 3; // Number of deleted files
}
